### ISSUE TITLE
How to use checkpoint?

### ISSUE THREAD

**Issue by jasonnwc97** [RUCAIBox/TextBox#118]
Hi,
"python run_textbox.py --model=RNN --dataset=COCO --task_type=unconditional --load_experiment=<ckpt_file> --test_only=true"
I try to use this command after the program stopped accidentally but it cannot find the ckpt_file so i am wondering where the ckpt_file will be and how to load them into the program. Looking forward for your reply! Thank you

**Comment by kuiyuli2** [comment]
Same issue here!
`    def resume_checkpoint(self, resume_file):`
        `"""Load the model parameters information and training information.
        Args:
            resume_file (file): the checkpoint file
        """`
        `resume_file = str(resume_file)`

changing the str(resume_file) doesn't seem to be working, where can I implement the previous checkpoint file to continue my experiment?

**Comment by StevenTang1998** [comment]
The `ckpt_file` file is located in the `saved` folder, for example, `--load_experiment=saved/RNN-COCO-Jan-29-2021_11-41-30.pth`.
