### ISSUE TITLE
detailed readme and documentation

### ISSUE THREAD

**Issue by zmf0507** [RUCAIBox/TextBox#125]
Hello ,
Thanks for developing such a nice library. I am looking for a detailed documentation. The readthedocs.io page is also empty and I feel the instructions given on github are not enough to run experiments. can you please share proper documentation for Textbox ? Moroever, If example notebooks/scripts can be shared , then it will be great for the first-time users to get started with training, evaluation, dataset loading as well decoding using different strategies like (beam, top_k etc). 

Thanks a lot .

**Comment by StevenTang1998** [comment]
Thank you for your suggestion. We will add detailed documentation later, but it may take a while.

You can directly leave a message here, if you have any questions, and we will answer them in time.

As for decoding strategies, you can change the `decoding_strategy` in [model].yaml.

**Comment by zmf0507** [comment]
okay. thanks. are you planning to add more decoding strategies like diverse beam search etc in the coming time? It will be great to have more decoding strategies. 
Moreover, we will get to see this today, right?  v0.2.1 | 15/04/2021 | TextBox

**Comment by StevenTang1998** [comment]
Thanks for your advice, we will take it into consideration. However, we are more focused on accommodating more models and common frameworks. We notice that the `generate` function in Hugging Face has already supported numerous decoding strategies, you can modify the code of `generate` in [model].py in our library and add parameters following [Hugging Face](https://huggingface.co/transformers/main_classes/model.html?highlight=generate#transformers.generation_utils.GenerationMixin.generate).

And we will release a new version today, thanks for your continued attention.
