### ISSUE TITLE
[Bug] RuntimeError: rnn: hx is not contiguous, when using vanilla encoder-decoer.

### ISSUE THREAD

**Issue by zhang-hengtong** [RUCAIBox/TextBox#142]
HOW TO REPRODUCE?

embedding_size: 128
hidden_size: 256
num_enc_layers: 2
bidirectional: True
num_dec_layers: 2
dropout_ratio: 0.2
rnn_type: "gru"
#attention_type: "LuongAttention"
#alignment_method: "concat"
beam_size: 5
decoding_strategy: 'beam_search'

----------------

model  RNNEncDec.
dataset IWSLT14_DE_EN

-----------------

Thanks for your attention.

**Comment by StevenTang1998** [comment]
I have fixed it and you can pull the latest one. Thanks for your report.
