### ISSUE TITLE
NotImplementedError: gpt2seq can't be found

### ISSUE THREAD

**Issue by will-wiki** [RUCAIBox/TextBox#143]
你好，想问下这个问题要如何解决呀

**Comment by StevenTang1998** [comment]
麻烦给一下运行指令

**Comment by will-wiki** [comment]
python run_textbox.py --model='GPT2Seq' \
        --test_only=False \
        --dataset='Lishipin_test' --gpu_id=1 --epochs=20 --learning_rate=1e-05 \
        --train_batch_size=4 --eval_batch_size=4

**Comment by StevenTang1998** [comment]
你好，我们并无法复现你的问题，请问你是否对源码进行了修改或者是否pull了最新的仓库？

**Comment by will-wiki** [comment]
pull的是你们最新的仓库，也就是近一周下载的TextBox项目，transformers==4.6.0，其他的模型都是正常的，但是gpt2seq这个模型就像问题一样找不到的。
因为我想在自己的中文数据集上做文本摘要，只修改了你们的transformers引用的模型以及数据处理部分的，一开始是下面这部分代码会报错
from transformers import GPT2LMHeadModel, GPT2TokenizerFast, GPT2Config
pretrained_model_path = 'ckiplab/gpt2-base-chinese'
tokenizer = GPT2TokenizerFast.from_pretrained("ckiplab/gpt2-base-chinese")
eos_token = tokenizer.eos_token
configuration = GPT2Config.from_pretrained(
    pretrained_model_path,
)
model = GPT2LMHeadModel.from_pretrained("ckiplab/gpt2-base-chinese")

报的错误类型是TypeError: expected str, bytes or os.PathLike object, not NoneType
于是我改成了一下代码,包括BART、T5模型都一样，原来的引用都会报上面那行的错误，改成下面的引用就能work，麻烦博主看看是哪部分有问题，这个gpt2seq为什么会找不到呢

from transformers import AutoTokenizer, AutoConfig, AutoModelForPreTraining,GPT2LMHeadModel,AutoModelWithLMHead
pretrained_model_path = 'ckiplab/gpt2-base-chinese'
tokenizer = AutoTokenizer.from_pretrained("ckiplab/gpt2-base-chinese")
eos_token = tokenizer.eos_token
configuration = AutoConfig.from_pretrained(
    pretrained_model_path,
)
model = AutoModelWithLMHead.from_pretrained("ckiplab/gpt2-base-chinese")

**Comment by StevenTang1998** [comment]
请问能否提供你修改后的完整代码，以及执行该代码，完整的日志和错误

**Comment by will-wiki** [comment]
不好意思....，应该是我代码改错了，已经解决了，十分感谢！
