### ISSUE TITLE
Questions about fast_bleu

### ISSUE THREAD

**Issue by wongchit** [RUCAIBox/TextBox#144]
The fast_bleu version in the fast_bleu_wheel4windows folder is 0.0.86, but the environment requirement is 0.0.89. In the Windows operating system, fast_bleu cannot be installed directly, can you please update the version in the fast_bleu_wheel4windows folder, thank you。

**Comment by StevenTang1998** [comment]
About the fast_bleu version of Windows, you can consult the original author.
And in general the fast_bleu version won't have a problem, you can just install 0.0.86.

**Comment by wongchit** [comment]
> 关于fast_bleu版本的Windows，可以咨询原作者。
> 而且一般fast_bleu版本不会有问题，安装0.0.86就可以了。

Verified, thank you very much
