### ISSUE TITLE
Given dataset has wrong in traing

### ISSUE THREAD

**Issue by Woeee** [RUCAIBox/TextBox#157]
I download Persona chat from BaiduWangpan that was given in README, but it may need more processes. 
In source code, it uses 'MultipleSentenceDataset' to deal with dialog task's dataset. Given dataset(persona chat) is split to source and target, and lacks knowledge part, which makes wrong in training. So I want to know more details about how to deal with this question, thank you~

**Comment by StevenTang1998** [comment]
You should pull the latest repository, we had a refactor in October.
