### ISSUE TITLE
question about  the kg2text task

### ISSUE THREAD

**Issue by jiangliqin** [RUCAIBox/TextBox#166]
Hi,
firstly, thanks a lot  for your work.
I have a question about the kg2text task in the project, no example and information about the kg2text, but i read your code, and found the kg dataset processor.
Could you please take some dataset and the corresponding model for example to further explain the kg2text details?

**Comment by StevenTang1998** [comment]
Thanks for your attention.
The KG2text task is still under test, and we will release detailed instruction in the next version.

**Comment by jiangliqin** [comment]
I'm looking forward your KG2text task research, and what's the roughly time about the next version?

**Comment by StevenTang1998** [comment]
It may be until February or March. We are working on papers recently.
We only support the GraphWriter (Text Generation from Knowledge Graphs with Graph Transformers) now, if you need it, we can provide instructions.

**Comment by jiangliqin** [comment]
ok,I need it,please give some instructions.
Actually it seems that the GraphWriter performance is not pretty good,  do u know the better KG2text model to suggest me?I will learn  from it,thanks!

**Comment by StevenTang1998** [comment]
Investigating Pretrained Language Models for Graph-to-Text Generation
Few-shot Knowledge Graph-to-Text Generation with Pretrained Language Models
KGPT Knowledge-Grounded Pre-Training for Data-to-Text Generation

Some kg2text papers, you can treat them as strong baselines. The intruction of GraphWriter will be released soon.

**Comment by jiangliqin** [comment]
awesome!Thanks again for your sharing!

**Comment by jiangliqin** [comment]
Hi,StevenTang, do you know the Chinese-related PLM for kg2text paper?Using the method of paper,I should prepare the large amount Chinese corpus to pretrain the model which is burdensome.

**Comment by StevenTang1998** [comment]
Sorry I know little about this.

**Comment by StevenTang1998** [comment]
We have upload the Agenda dataset in Baidu WangPan.
You can pull the lastest repository and run the following command:
python run_textbox.py --model=Kb2Text --dataset=Agenda

**Comment by jiangliqin** [comment]
get it, thanks for syncing it to me in time

**Comment by jiangliqin** [comment]
similar to kg2text, the table2text task is also needed, how long will you release the table2text details?

**Comment by StevenTang1998** [comment]
The table2text model is a little outdated, and may not be a good choice as a baseline. You can use PLMs with linearized table.

**Comment by jiangliqin** [comment]
fine, my weChat is “hashenbb”, could you add my weChat for text generation discussion?
