### ISSUE TITLE
Lack of portability on Windows

### ISSUE THREAD

**Issue by huyiwen** [RUCAIBox/TextBox#183]
In [textbox/data/utils.py](https://github.com/RUCAIBox/TextBox/blob/main/textbox/data/utils.py)

- Line 16 `from posix import listdir` should be `from os import listdir`,  which resulted a lack of portability on Windows. 
- Line 259 `with open(dataset_path, "r") as fin:` should specify encoding to `utf-8`.

[posix: Do not import this module directly.](https://docs.python.org/3/library/posix.html)

**Comment by StevenTang1998** [comment]
Thanks for your report. However, considering the act
