### ISSUE TITLE
TextBox train.py error and possible solutions

### ISSUE THREAD

**Issue by hanchi-gao** [RUCAIBox/TextBox#262]
get the error In follow image 
`  File "/textbox/Textbox_test/TextBox/textbox/trainer/trainer.py", line 516, in evaluate
    generated = self.accelerator.unwrap_model(self.model).generate(batch_data, self.accelerator)
TypeError: generate() missing 1 required positional argument: 'accelerator'`
![image](https://user-images.githubusercontent.com/56921951/194307304-7ebd647e-6e63-4976-84f6-78742c9c31ff.png)

I compared the older version:
latest version
line 516: `generated = self.accelerator.unwrap_model(self.model).generate(batch_data, self.accelerator`
older version 
line 505: `generated = self.accelerator.unwrap_model(self.model).generate(batch_data, eval_data, self.accelerator)`

so, I added the argument "eval_data" to generate().
Sure enough, problem solved.
Please confirm this error

**Comment by StevenTang1998** [comment]
Thank you for pointing out this issue. We have removed the argument `eval_data` in the `generate` function.
