### ISSUE TITLE
Text Generation Using SeqGAN 

### ISSUE THREAD

**Issue by hmqt** [RUCAIBox/TextBox#300]
Hi, 
After I trained the SeqGAN Model on Arabic texts I have a generated file (SeqGAN-wiki_ar-Dec-05-2022_20-05-03.txt) which contains a huge number of Arabic-generated sentences. 
But my question to you is, is it possible for me, after the end of the training period for this model (which was approximately three days), to run it in order to get a new sentence that was just generated every time, immediately? 
Does TextBox tools support this feature and how can I run the SeqGAN after training on the special dataset to generate a new sentence every time?

**Comment by StevenTang1998** [comment]
If you has already trained a model in the `saved` folder named `SeqGAN-dataset-time.pth`, you can load it and just generate sentences by adding the command `--test_only=True --load_experiment=saved/SeqGAN-dataset-time.pt` to your original command.

**Comment by hmqt** [comment]
Thank you so much
