### ISSUE TITLE
Custom Dataset Preprocessing

### ISSUE THREAD

**Issue by imamnurby** [RUCAIBox/TextBox#314]
Does TextBox support custom  preprocessing for a dataset?

I work with source code data, and such data may require custom preprocessing. For example, extracting abstract syntax tree, or dataflow graph.

**Comment by StevenTang1998** [comment]
Sorry, we don't support it at the moment. You can preprocess your data into a text-to-text format before feeding to TextBox.

**Comment by imamnurby** [comment]
Thanks for the prompt response.

It would be nice feature in the future if we can plug custom preprocessing in the pipeline :)

**Comment by StevenTang1998** [comment]
Thanks for your understanding. Could you tell us the task you are working on? Or a detailed dataflow pipeline?

**Comment by imamnurby** [comment]
My task is translating source code to source code.

The example use case is [this](https://github.com/microsoft/CodeBERT/blob/305bab27920d57ba37964ab05ee7b1acdbb24416/GraphCodeBERT/translation/run.py#L419).

**Comment by StevenTang1998** [comment]
got it!
