### ISSUE TITLE
Not worked one-to-many dataset for machine learning

### ISSUE THREAD

**Issue by BabylenMagnus** [RUCAIBox/TextBox#322]
example of data:
`train.src`
```
ABC
BCA
```
`train.tgt`
```
['Abc', 'ABc']
'bca'
```
the `textbox/properties/dataset/my_data.yaml` dataset config is same as `textbox/properties/dataset/wmt19-ru-en.yaml` 

command:
```terminal
python run_textbox.py --model=BART --dataset=my_data  --model_path=facebook/bart-base
```

I got the following error from tokenizer `transformers.AutoTokenizer`:
```
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```
error occurs in the method of the `textbox.data.abstract_dataset.AbstractDataset` class on 127 line.
```python
target_ids = tokenizer(
    text_target=self.target_text,
    add_special_tokens=False,
    return_token_type_ids=False,
    return_attention_mask=False,
)["input_ids"]
```
It caused due that the `self.target_text` is created by the `textbox.data.misc.load_data` function
```
def load_data(dataset_path: str, max_length: int = 0):
...
    text = []
    with open(dataset_path, "r") as fin:
        if max_length:
            fin = itertools.islice(fin, max_length)
        for line in fin:
            l = line.strip()
            if len(l) >= 2 and ((l[0] == '"' and l[-1] == '"') or (l[0] == "'" and l[-1] == "'") or
                                (l[0] == '[' and l[-1] == ']')):
                try:
                    l = eval(l)
                    if not isinstance(l, list):
                        l = str(l)
                except:
                    pass
            text.append(l)
    return text
```
this function return from my_data `[['Abc', 'ABc'], 'bca']` and that structure not follow requirement of transformers.AutoTokenizer - Union[TextInputSequence, Tuple[InputSequence, InputSequence]].  

are there examples of learning a machine learning model with a one-to-many dataset?

**Comment by StevenTang1998** [comment]
https://github.com/RUCAIBox/TextBox/issues/321#issuecomment-1398038344
You should follow this in detail! `"['Abc', 'ABc']"` rather than `['Abc', 'ABc']`
The `tgt` should use the repr expression of Python.

**Comment by StevenTang1998** [comment]
For example
```python
>>> a = ['abc', 'ABC']
>>> a
['abc', 'ABC']
>>> repr(a)
"['abc', 'ABC']"
>>> eval("['abc', 'ABC']")
['abc', 'ABC']
```

**Comment by BabylenMagnus** [comment]
thank you so much
