### ISSUE TITLE
[🐛BUG] The bug of T5 using prefix-tuning

### ISSUE THREAD

**Issue by luoyetingqiu** [RUCAIBox/TextBox#331]
**Describe the bug**
AttributeError: 'GPT2LMHeadModel' object has no attribute 'set_efficient_tuning'

When I use efficient_methods：

python run_textbox.py \
    --model=T5 \
    --model_path=t5-large \
    --dataset=webnlg \
    --gpu_id=4 \
    --efficient_methods=\[\'prefix-tuning\'\] \
    --efficient_kwargs=\{\'prefix_length\':\ 100,\ \'prefix_dropout\':\ 0.1,\ \'prefix_mid_dim\':\ 512\} \
    --filename CP/T5_large_prefix_tuning

**Comment by StevenTang1998** [comment]
You need to install our Transformers following the [instruction](https://github.com/RUCAIBox/TextBox#installation).
Or using `pip install git+https://github.com/RUCAIBox/transformers.git`
