### ISSUE TITLE
[🐛BUG] RUCAIBox/StyleTransfer里面的gyafc_em.ckpt文件缺失

### ISSUE THREAD

**Issue by Arthas183** [RUCAIBox/TextBox#332]
在运行
python  run_textbox.py  --model=OpenAI-GPT  --model_path=openai-gpt  --dataset=gyafc_em
的时候，会报错
[Errno 2] No such file or directory: 'textbox/evaluator/utils/gyafc_em.ckpt'
在使用RUCAIBox/StyleTransfer里面的GYAFC数据集的时候他需要这个ckpt文件，请问在哪里下载或者生成？

**Comment by StevenTang1998** [comment]
我们已经上传，麻烦重新pull仓库即可

**Comment by Arthas183** [comment]
> 我们已经上传，麻烦重新pull仓库即可

好的谢谢，已经可以使用了。

另外还想请教一句，在设置了单机多卡训练之后，为什么他会卡在这里：
运行指令是：
accelerate launch run_textbox.py --model=Chinese-GPT2 --model_path=ckiplab/gpt2-base-chinese --dataset=gyafc_fr --gpu_id=0,1,2
运行过程：
24 Mar 08:18    INFO ====== Finished training, best validation result at train epoch 1 ======
24 Mar 08:18    INFO Best valid result: score: 4.78, bleu: 6.88, style: 3.66, <hm: 4.78>
24 Mar 08:18    INFO Loading model structure and parameters from saved/Chinese-GPT2-gyafc_fr-2023-Mar-24_08-13-11/checkpoint_best ...
输出到这里就停下卡住不动了。从nvidia-smi上看，从这里开始就剩第0号卡继续满负荷工作了。这里是bug吗？

**Comment by StevenTang1998** [comment]
最新的pr已经解决了这个问题，麻烦再pull一下，感谢报告！

**Comment by Arthas183** [comment]
> 最新的pr已经解决了这个问题，麻烦再pull一下，感谢报告！

好的，辛苦您了！
您这边方便的话，我会把我使用过程中遇到的问题都发到这里。
目前在运行
python run_textbox.py  --model=BART  --model_path=facebook/bart-base  --dataset=gyafc_em 
的时候，generate的过程中会报warning
"A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer."
请问这个padding_side=left的选项是在什么地方设置呢？

**Comment by StevenTang1998** [comment]
我们似乎不能复现这个问题，理论上BART是一个encoder-decoder模型而不是decoder-only的

**Comment by Arthas183** [comment]
> 我们似乎不能复现这个问题，理论上BART是一个encoder-decoder模型而不是decoder-only的

好的，我运行很多模型（GPT2/BART/openai-GPT）都出这个问题，我先试试这个办法吧：https://stackoverflow.com/questions/74748116/huggingface-automodelforcasuallm-decoder-only-architecture-warning-even-after
把transformers版本降到4.22.2就可以消除这个错误。
也就是说（如果您方便的话）可以在随后的更新中给requirements.txt加上版本号，这样会少很多错误。

**Comment by StevenTang1998** [comment]
抱歉，我们是基于transformers 4.26.0来开发的，并且warning不是error，只消除warning并不会带来结果的变化，我们原来的方法并不会导致结果错误。
关于GPT-2的warning我们已经修改，麻烦pull最新仓库。
由于我们实在无法在BART复现这个warning，能否麻烦提供运行的project.log来方便我们进行分析。

**Comment by Arthas183** [comment]
> 抱歉，我们是基于transformers 4.26.0来开发的，并且warning不是error，只消除warning并不会带来结果的变化，我们原来的方法并不会导致结果错误。 关于GPT-2的warning我们已经修改，麻烦pull最新仓库。 由于我们实在无法在BART复现这个warning，能否麻烦提供运行的project.log来方便我们进行分析。

抱歉我重新看了一下运行的代码，应该是这两条报的这个warning:  BART是好的。

python run_textbox.py --model=OpenAI-GPT --model_path=openai-gpt --dataset=gyafc_em
python run_textbox.py --model=GPT2 --model_path=gpt2 --dataset=gyafc_fr

project如下，但里面没有报错信息。
[gpt2-project.log](https://github.com/RUCAIBox/TextBox/files/11073885/gpt2-project.log)
[openai-gpt-project.log](https://github.com/RUCAIBox/TextBox/files/11073887/openai-gpt-project.log)

图片传不上来，我复制报错文字吧。用的是VSCode编辑器。

generating:  52%|██████████████████▊                 | 11/21 [00:21<00:20,  2.01s/it]A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
generating:  57%|████████████████████▌               | 12/21 [00:23<00:17,  2.00s/it]A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
generating:  62%|██████████████████████▎             | 13/21 [00:25<00:16,  2.01s/it]A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

**Comment by StevenTang1998** [comment]
关于GPT-2的warning我们已经修改，麻烦pull最新仓库。

**Comment by Arthas183** [comment]
> 关于GPT-2的warning我们已经修改，麻烦pull最新仓库。

抱歉，刚才更新了仓库，多卡训练已经可以正常使用了，谢谢！
只是这个openai-gpt2和GPT2报“A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set padding_side='left' when initializing the tokenizer.”的问题依然存在。

如果这个warning不影响结果的话，那我忽略他好了。

**Comment by StevenTang1998** [comment]
我们已经解决了GPT-2的这个问题，能麻烦更新一下后再试一下吗？

**Comment by Arthas183** [comment]
> 我们已经解决了GPT-2的这个问题，能麻烦更新一下后再试一下吗？

谢谢！这次已经解决了！非常感谢您的帮助！！
