### ISSUE TITLE
[💡SUG] 想请问一下PTG的那个pth文件是怎么做出来的，里面具体包含什么

### ISSUE THREAD

**Issue by Arthas183** [RUCAIBox/TextBox#348]
最近拜读了这篇论文Learning to transfer prompts for text generation (https://github.com/RUCAIBox/Transfer-Prompts-for-Text-Generation)
想请教一下这个prompt_source.pth文件里面包含的是什么样的prompt。
我读了一下这个文件发现里面只有很多200*1024大小的tensor，但不知道这些tensor的具体含义。

**Comment by StevenTang1998** [comment]
就是论文中的E_p，每个数据集学一个这样的tensor

**Comment by Arthas183** [comment]
> 就是论文中的E_p，每个数据集学一个这样的tensor

好的好的，可能我应该这么请教一下：我应该怎么去生成这个prompt_source文件，用什么样的中文或者英文prompt，怎么做？
纯新手上路，还望大佬指导指导

**Comment by StevenTang1998** [comment]
这个建议先仔细阅读论文和相关工作（尤其是prompt tuning）吧，大致说就是冻结PLM，用一个数据集去训练一个prompt

**Comment by Arthas183** [comment]
> 这个建议先仔细阅读论文和相关工作（尤其是prompt tuning）吧，大致说就是冻结PLM，用一个数据集去训练一个prompt

好的好的，另外想请问下，yaml文件里面有一个hm指标，这是什么指标呢，我在网上找不到具体解释。

**Comment by StevenTang1998** [comment]
请阅读我们首页的论文，里面有相关介绍

**Comment by StevenTang1998** [comment]
如果有问题欢迎继续提问
