### ISSUE TITLE
Ran Model after training

### ISSUE THREAD

**Issue by hmqt** [RUCAIBox/TextBox#350]
how i can run my mode after training it on my data

**Comment by StevenTang1998** [comment]
Could you provide more detailed information?

**Comment by hmqt** [comment]
i trained my dataset (novels) on SeqGAN model and i got this file SeqGAN-novels-Apr-23-2023_23-30-28.pth. How i can used this file to generate arabic texts any time any moment.

**Comment by StevenTang1998** [comment]
You can add `--test_only=True --load_experiment=saved/SeqGAN-novels-Apr-23-2023_23-30-28.pth` to your initial command. It will generate as many examples as your test set.

**Comment by Rutheniumlmw** [comment]
我同样想知道怎么在训练之后运行模型，但我训练完之后并没有得到.pth文件。我的训练命令是 `python run_textbox.py --model=BART --dataset=samsum --model_path=facebook/bart-base`。得到一个checkpoint_best文件夹，请教一下怎么使用训练得到的模型
