### ISSUE TITLE
[💡SUG] 我想使用huggingface上已有的模型不经过训练和验证直接对数据集进行测试

### ISSUE THREAD

**Issue by 01vanilla** [RUCAIBox/TextBox#353]
**添加新功能**
我想要使用huggingface上已经有的模型进行文本生成，例如，我想用huggingface上的t5-small模型直接对SAMsum数据集进行摘要并生成评价指标应该如何操作

**您的贡献**
您有一些可能的解决方案吗？您能否通过提交PR帮助我们？

**Comment by StevenTang1998** [comment]
运行命令加上`--do_train=False --do_valid=False`即可，例如
```
python run_textbox.py --model=T5 --model_path=t5-small --dataset=samsum --do_train=False --do_valid=False
```
