### ISSUE TITLE
how can we generate text?

### ISSUE THREAD

**Issue by ridvantaskiran** [RUCAIBox/TextBox#365]
As far as I understand, there is everything related to model training and analysis of generated texts, but I could not find how we can generate texts with given input. Can someone help me?

**Comment by StevenTang1998** [comment]
Could you detail your requirements? Which model or dataset do you want?

**Comment by ridvantaskiran** [comment]
I am working on story generation. I haven't decided on the model yet but I can start with the BART model and ROCStories dataset. After the model selection, I will work with my own Turkish dataset

**Comment by StevenTang1998** [comment]
You can follow the instruction [here](https://github.com/RUCAIBox/TextBox/blob/2.0.0/asset/dataset.md#new-dataset) to add your own dataset.

**Comment by ridvantaskiran** [comment]
Thanks, how about generating stories with the given input?

**Comment by StevenTang1998** [comment]
You just need to write them in the `test.src`. Then, after the model training, it will generate the output.

**Comment by ridvantaskiran** [comment]
Thank you for your help and time
