### ISSUE TITLE
FAQ: Results of other seq2seq models 

### ISSUE THREAD

**Issue by shiningliang** [RUCAIBox/TextBox#92]
Nice work and thank you for your team's contribution.
FYI. As for the seq2seq generation results of GPT/BART etc. do you plan to release?

**Comment by StevenTang1998** [comment]
We will release the results later.
Some models are still running because of computational force. We will release results for RNN, Transformer, BART in ISWLT, WMT and GigaWord within a week. The results of other models will be released in succession.

**Comment by shiningliang** [comment]
Thanks!
