### ISSUE TITLE
Add support for REINFORCE training

### ISSUE THREAD

**Issue by mukhal** [RUCAIBox/TextBox#93]
Hello,

Thank you for this tool. I would like to add the possibility of training using Reinforcement Learning using a reward such as ROUGE or BLEU, for seq2seq tasks.

I would be happy to contribute!

Best,
Muhammad

**Comment by turboLJY** [comment]
Everyone is welcome to contribute this project. You can pull requests and we would include it into our repository after verified. Thank you!
