### ISSUE TITLE
Windows上安装失败

### ISSUE THREAD

**Issue by yuganqun** [RUCAIBox/TextBox#95]
fast-bleu在windows上编译失败，可否提供一下fast-bleu的wheel文件？

**Comment by StevenTang1998** [comment]
We are sorry to find that fast-bleu does not support Windows at the moment, we are also exploring a solution to try to solve it in the next version.
You can also calculate BLEU using `nltk.translate.bleu_score` in `evaluator/metrics.py`.

**Comment by yizhangliu** [comment]
@yuganqun 
> 
> fast-bleu在windows上编译失败，可否提供一下fast-bleu的wheel文件？

I uploaded a project. You can refer to it.    [fast-bleu_windows_vs2019](https://github.com/yizhangliu/fast-bleu_windows_vs2019)

**Comment by StevenTang1998** [comment]
@yizhangliu Thanks for your support.
@yuganqun We have add support Windows for fast_bleu, you can follow the guide [https://github.com/RUCAIBox/TextBox#install-from-pip](https://github.com/RUCAIBox/TextBox#install-from-pip) to install fast_bleu for Windows.
